import { Image as ImageIcon, Maximize2, Download } from 'lucide-react';

export function CampaignCreatives({ campaign }: any) {
  const { strategy } = campaign;
  const defaultImages = [
    "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&q=80",
    "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&q=80"
  ];
  const creatives = strategy?.creatives?.length > 0 ? strategy.creatives : defaultImages;

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
      <div className="p-6 border-b border-gray-100 flex items-center gap-2">
        <ImageIcon className="h-5 w-5 text-purple-500" />
        <h3 className="text-sm font-bold text-gray-900">Campaign Creatives</h3>
      </div>
      <div className="p-4 bg-[#F8FAFC] flex flex-col gap-4">
        {creatives.map((creativeUrl: string, index: number, arr: any[]) => (
          <div key={index} className="rounded-2xl overflow-hidden shadow-sm relative group aspect-[4/5]">
            <img 
              src={creativeUrl.startsWith('http') || creativeUrl.startsWith('data:') ? creativeUrl : `data:image/jpeg;base64,${creativeUrl}`} 
              alt={`Creative ${index + 1}`} 
              className="w-full h-full object-cover bg-gray-100" 
              onError={(e) => {
                e.currentTarget.onerror = null;
                e.currentTarget.src = "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&q=80";
              }}
            />
            <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col justify-between p-4">
              <div className="flex justify-end gap-2">
                <a href={creativeUrl} target="_blank" rel="noopener noreferrer" className="p-2 bg-white/20 hover:bg-white/40 rounded-full text-white backdrop-blur-sm transition-colors" title="Preview in new tab">
                  <Maximize2 className="w-4 h-4" />
                </a>
                <a href={creativeUrl} download={`creative-${index + 1}.jpg`} className="p-2 bg-white/20 hover:bg-white/40 rounded-full text-white backdrop-blur-sm transition-colors" title="Download">
                  <Download className="w-4 h-4" />
                </a>
              </div>
              <div className="flex items-end justify-between">
                <span className="text-white text-xs font-bold tracking-wider uppercase drop-shadow-md">Generated by AI</span>
                <span className="text-white/90 text-xs font-bold tracking-wider drop-shadow-md">{index + 1} of {arr.length}</span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
